# Generated by Django 4.2 on 2025-02-20 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recommendation",
            options={"ordering": ["-recommendation_date"]},
        ),
        migrations.AddField(
            model_name="recommendation",
            name="draw_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="draw_round",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="is_checked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="is_won",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="recommendation_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="numbers",
            field=models.CharField(max_length=20),
        ),
    ]
