# Generated by Django 4.2 on 2025-02-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_alter_recommendation_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recommendation",
            name="created_at",
        ),
        migrations.AddField(
            model_name="recommendation",
            name="has_bonus",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="matched_count",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="rank",
            field=models.IntegerField(null=True),
        ),
    ]
